services:
  - type: web
    name: ampypay
    runtime: python
    rootDir: .
    buildCommand: echo "no build step"
    startCommand: python3 server.py
    envVars:
      - key: PORT
        value: 10000
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_SECURE
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: NOTIFY_EMAIL
        sync: false
      - key: ADMIN_TOKEN
        sync: false
      - key: TURNSTILE_SECRET
        sync: false
